<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class charity_supportForm extends Model
{
    //
    public function fields()
    {
        return $this->hasMany('App\charity_supportForm_filds', 'ch_s_form_id');
    }
    public function delete()
    {
        $this->fields()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
